market:
  port: 5001
  address: localhost
broker:
  port: 5000
  address: localhost

spring:
  datasource:
    url: jdbc:h2:mem:tdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect